<?php

use App\Enums\IntegrationActionType;
use App\Enums\IntegrationDestinationType;

return [
    'default_locale' => 'es',
    'supported_locales' => ['es', 'en'],
    'actions' => [
        'es' => [
            IntegrationActionType::Book->value => 'Reservar cita',
            IntegrationActionType::Contact->value => 'Contactar',
            IntegrationActionType::Download->value => 'Descargar documento',
            IntegrationActionType::ListenOn->value => 'Escuchar en :destination',
            IntegrationActionType::ListenTo->value => 'Escuchar :destination',
            IntegrationActionType::OpenIn->value => 'Abrir en :destination',
            IntegrationActionType::ReadOn->value => 'Leer en :destination',
            IntegrationActionType::ShopOn->value => 'Comprar en :destination',
            IntegrationActionType::View->value => 'Ver :destination',
            IntegrationActionType::ViewOn->value => 'Ver en :destination',
            IntegrationActionType::Visit->value => 'Visitar :destination',
        ],
        'en' => [
            IntegrationActionType::Book->value => 'Book appointment',
            IntegrationActionType::Contact->value => 'Contact',
            IntegrationActionType::Download->value => 'Download document',
            IntegrationActionType::ListenOn->value => 'Listen on :destination',
            IntegrationActionType::ListenTo->value => 'Listen to :destination',
            IntegrationActionType::OpenIn->value => 'Open in :destination',
            IntegrationActionType::ReadOn->value => 'Read on :destination',
            IntegrationActionType::ShopOn->value => 'Shop on :destination',
            IntegrationActionType::View->value => 'View :destination',
            IntegrationActionType::ViewOn->value => 'View on :destination',
            IntegrationActionType::Visit->value => 'Visit :destination',
        ],
    ],
    'destinations' => [
        IntegrationDestinationType::Instagram->value => ['action' => IntegrationActionType::ViewOn->value, 'es' => 'Instagram', 'en' => 'Instagram'],
        IntegrationDestinationType::Tiktok->value => ['action' => IntegrationActionType::ViewOn->value, 'es' => 'TikTok', 'en' => 'TikTok'],
        IntegrationDestinationType::Facebook->value => ['action' => IntegrationActionType::ViewOn->value, 'es' => 'Facebook', 'en' => 'Facebook'],
        IntegrationDestinationType::Youtube->value => ['action' => IntegrationActionType::ViewOn->value, 'es' => 'YouTube', 'en' => 'YouTube'],
        IntegrationDestinationType::X->value => ['action' => IntegrationActionType::ViewOn->value, 'es' => 'X / Twitter', 'en' => 'X / Twitter'],
        IntegrationDestinationType::Threads->value => ['action' => IntegrationActionType::ViewOn->value, 'es' => 'Threads', 'en' => 'Threads'],
        IntegrationDestinationType::Linkedin->value => ['action' => IntegrationActionType::ViewOn->value, 'es' => 'LinkedIn', 'en' => 'LinkedIn'],
        IntegrationDestinationType::Pinterest->value => ['action' => IntegrationActionType::ViewOn->value, 'es' => 'Pinterest', 'en' => 'Pinterest'],
        IntegrationDestinationType::Snapchat->value => ['action' => IntegrationActionType::ViewOn->value, 'es' => 'Snapchat', 'en' => 'Snapchat'],
        IntegrationDestinationType::Reddit->value => ['action' => IntegrationActionType::ViewOn->value, 'es' => 'Reddit', 'en' => 'Reddit'],
        IntegrationDestinationType::Whatsapp->value => ['action' => IntegrationActionType::OpenIn->value, 'es' => 'WhatsApp', 'en' => 'WhatsApp'],
        IntegrationDestinationType::Telegram->value => ['action' => IntegrationActionType::OpenIn->value, 'es' => 'Telegram', 'en' => 'Telegram'],
        IntegrationDestinationType::Discord->value => ['action' => IntegrationActionType::OpenIn->value, 'es' => 'Discord', 'en' => 'Discord'],
        IntegrationDestinationType::Twitch->value => ['action' => IntegrationActionType::ViewOn->value, 'es' => 'Twitch', 'en' => 'Twitch'],
        IntegrationDestinationType::Spotify->value => ['action' => IntegrationActionType::ListenOn->value, 'es' => 'Spotify', 'en' => 'Spotify'],
        IntegrationDestinationType::AppleMusic->value => ['action' => IntegrationActionType::ListenOn->value, 'es' => 'Apple Music', 'en' => 'Apple Music'],
        IntegrationDestinationType::Podcast->value => ['action' => IntegrationActionType::ListenTo->value, 'es' => 'Podcast', 'en' => 'Podcast', 'action_es' => 'el podcast', 'action_en' => 'the podcast'],
        IntegrationDestinationType::NewsMedia->value => ['action' => IntegrationActionType::ReadOn->value, 'es' => 'Diario / Medio', 'en' => 'News / Media', 'action_es' => 'el medio', 'action_en' => 'the news outlet'],
        IntegrationDestinationType::Magazine->value => ['action' => IntegrationActionType::ReadOn->value, 'es' => 'Revista', 'en' => 'Magazine', 'action_es' => 'la revista', 'action_en' => 'the magazine'],
        IntegrationDestinationType::Blog->value => ['action' => IntegrationActionType::ReadOn->value, 'es' => 'Blog', 'en' => 'Blog', 'action_es' => 'el blog', 'action_en' => 'the blog'],
        IntegrationDestinationType::Newsletter->value => ['action' => IntegrationActionType::ReadOn->value, 'es' => 'Newsletter', 'en' => 'Newsletter', 'action_es' => 'el newsletter', 'action_en' => 'the newsletter'],
        IntegrationDestinationType::Medium->value => ['action' => IntegrationActionType::ReadOn->value, 'es' => 'Medium', 'en' => 'Medium'],
        IntegrationDestinationType::Substack->value => ['action' => IntegrationActionType::ReadOn->value, 'es' => 'Substack', 'en' => 'Substack'],
        IntegrationDestinationType::OnlineStore->value => ['action' => IntegrationActionType::ShopOn->value, 'es' => 'Tienda en línea', 'en' => 'Online store', 'action_es' => 'la tienda en línea', 'action_en' => 'the online store'],
        IntegrationDestinationType::Marketplace->value => ['action' => IntegrationActionType::ShopOn->value, 'es' => 'Marketplace', 'en' => 'Marketplace', 'action_es' => 'el marketplace', 'action_en' => 'the marketplace'],
        IntegrationDestinationType::Amazon->value => ['action' => IntegrationActionType::ShopOn->value, 'es' => 'Amazon', 'en' => 'Amazon'],
        IntegrationDestinationType::MercadoLibre->value => ['action' => IntegrationActionType::ShopOn->value, 'es' => 'Mercado Libre', 'en' => 'Mercado Libre'],
        IntegrationDestinationType::Membership->value => ['action' => IntegrationActionType::View->value, 'es' => 'Membresía', 'en' => 'Membership', 'action_es' => 'la membresía', 'action_en' => 'the membership'],
        IntegrationDestinationType::Portfolio->value => ['action' => IntegrationActionType::View->value, 'es' => 'Portafolio', 'en' => 'Portfolio', 'action_es' => 'el portafolio', 'action_en' => 'the portfolio'],
        IntegrationDestinationType::Behance->value => ['action' => IntegrationActionType::ViewOn->value, 'es' => 'Behance', 'en' => 'Behance'],
        IntegrationDestinationType::Github->value => ['action' => IntegrationActionType::ViewOn->value, 'es' => 'GitHub', 'en' => 'GitHub'],
        IntegrationDestinationType::Course->value => ['action' => IntegrationActionType::View->value, 'es' => 'Curso', 'en' => 'Course', 'action_es' => 'el curso', 'action_en' => 'the course'],
        IntegrationDestinationType::Event->value => ['action' => IntegrationActionType::View->value, 'es' => 'Evento', 'en' => 'Event', 'action_es' => 'el evento', 'action_en' => 'the event'],
        IntegrationDestinationType::Booking->value => ['action' => IntegrationActionType::Book->value, 'es' => 'Reservas / Citas', 'en' => 'Bookings / Appointments'],
        IntegrationDestinationType::Document->value => ['action' => IntegrationActionType::Download->value, 'es' => 'Documento / PDF', 'en' => 'Document / PDF'],
        IntegrationDestinationType::Application->value => ['action' => IntegrationActionType::OpenIn->value, 'es' => 'Aplicación', 'en' => 'Application', 'action_es' => 'la aplicación', 'action_en' => 'the app'],
        IntegrationDestinationType::Website->value => ['action' => IntegrationActionType::Visit->value, 'es' => 'Sitio web', 'en' => 'Website', 'action_es' => 'el sitio web', 'action_en' => 'the website'],
        IntegrationDestinationType::ContactPage->value => ['action' => IntegrationActionType::Contact->value, 'es' => 'Página de contacto', 'en' => 'Contact page'],
        IntegrationDestinationType::Other->value => ['action' => IntegrationActionType::ViewOn->value, 'es' => 'Otro', 'en' => 'Other'],
    ],
];
