<?php

return [
    'default_plan' => env('SUBSCRIPTION_DEFAULT_PLAN', 'starter'),
    'customer_terms_version' => env('SUBSCRIPTION_CUSTOMER_TERMS_VERSION', '2026-07-29'),

    'trial' => [
        'enabled' => env('SUBSCRIPTION_FREE_TRIAL_ENABLED', true),
        'days' => (int) env('SUBSCRIPTION_FREE_TRIAL_DAYS', 7),
        'setup_amount_usd' => (float) env('SUBSCRIPTION_TRIAL_SETUP_AMOUNT_USD', 0),
        'requires_payment_source' => env('SUBSCRIPTION_FREE_TRIAL_REQUIRES_PAYMENT_SOURCE', true),
    ],

    'plans' => [
        'starter' => [
            'name' => 'Starter',
            'active' => true,
            'visible' => true,
            'assignable' => true,
            'purchasable' => true,
            'price_usd' => 9.99,
            'currency' => 'USD',
            'interval' => 'monthly',
            'usage_interval' => 'monthly',
            'limits' => [
                'profiles' => 1,
                'avatar_images' => 1,
                'avatar_video_seconds' => 5,
                'voice_clones' => 1,
                'tts_characters' => 10000,
                'chat_messages' => 1000,
            ],
            'credits' => [
                'total' => 1000,
                'allocations' => [
                    'chat_messages' => [
                        'credits' => 500,
                        'units' => 1000,
                        'unit' => 'messages',
                        'units_per_credit' => 2,
                    ],
                    'tts_characters' => [
                        'credits' => 500,
                        'units' => 10000,
                        'unit' => 'characters',
                        'units_per_credit' => 20,
                    ],
                ],
            ],
            'cost_assumptions' => [
                'avatar_images' => [
                    'provider' => 'Runway',
                    'service' => 'gen4_image',
                    'unit' => 'Imagen 720p',
                    'volume' => 1,
                    'base' => 'USD 0.01 por credito; 5 creditos por imagen 720p',
                    'calculated_base' => 5,
                    'cost_usd' => 0.05,
                    'notes' => 'Si se genera en 1080p, cambiar creditos por imagen de 5 a 8.',
                ],
                'avatar_video_seconds' => [
                    'provider' => 'Runway',
                    'service' => 'gen4.5',
                    'unit' => 'Video de 5 segundos',
                    'volume' => 5,
                    'base' => '12 creditos por segundo',
                    'calculated_base' => 60,
                    'cost_usd' => 0.60,
                    'notes' => 'Duracion editable desde videoai.default_duration.',
                ],
                'voice_clones' => [
                    'provider' => 'ElevenLabs',
                    'service' => '/v1/voices/add',
                    'unit' => '1 voz clonada',
                    'volume' => 1,
                    'base' => 'Sin costo variable directo modelado',
                    'calculated_base' => 0,
                    'cost_usd' => 0.00,
                    'notes' => 'Crear la voz habilita un voice_id. TTS se cobra por caracteres.',
                ],
                'tts_characters' => [
                    'provider' => 'ElevenLabs',
                    'service' => 'eleven_multilingual_v2',
                    'unit' => '10,000 caracteres',
                    'volume' => 10000,
                    'base' => '1 credito por caracter; equivalente segun plan',
                    'calculated_base' => 10000,
                    'cost_usd' => 2.00,
                    'notes' => 'Costo imputado Starter: USD 6 / 30k creditos = USD 2.00.',
                ],
                'chat_messages' => [
                    'provider' => 'OpenAI',
                    'service' => 'gpt-4o-mini',
                    'unit' => '1,000 mensajes',
                    'volume' => 1000,
                    'base' => 'USD 0.15/M input + USD 0.60/M output',
                    'calculated_base' => 1500000,
                    'cost_usd' => 0.68,
                    'notes' => 'Si se migra de modelo, actualizar precios en Supuestos.',
                ],
            ],
            'estimated_total_cost_usd' => 3.33,
        ],
        'starter_annual' => [
            'name' => 'Starter',
            'active' => true,
            'visible' => true,
            'assignable' => true,
            'purchasable' => true,
            'price_usd' => 99.00,
            'currency' => 'USD',
            'interval' => 'annual',
            'usage_interval' => 'monthly',
            'limits' => [
                'profiles' => 1,
                'avatar_images' => 1,
                'avatar_video_seconds' => 5,
                'voice_clones' => 1,
                'tts_characters' => 10000,
                'chat_messages' => 1000,
            ],
            'credits' => [
                'total' => 1000,
                'allocations' => [
                    'chat_messages' => [
                        'credits' => 500,
                        'units' => 1000,
                        'unit' => 'messages',
                        'units_per_credit' => 2,
                    ],
                    'tts_characters' => [
                        'credits' => 500,
                        'units' => 10000,
                        'unit' => 'characters',
                        'units_per_credit' => 20,
                    ],
                ],
            ],
            'estimated_total_cost_usd' => 39.96,
        ],
        'admin' => [
            'name' => 'Admin',
            'active' => true,
            'price_usd' => 0.00,
            'currency' => 'USD',
            'interval' => 'monthly',
            'usage_interval' => 'monthly',
            'visible' => false,
            'assignable' => true,
            'purchasable' => false,
            'unlimited' => true,
            'limits' => [
                'profiles' => 2147483647,
                'avatar_images' => 2147483647,
                'avatar_video_seconds' => 2147483647,
                'voice_clones' => 2147483647,
                'tts_characters' => 2147483647,
                'chat_messages' => 2147483647,
            ],
            'credits' => [
                'total' => 99999999.99,
                'allocations' => [],
            ],
        ],
        'pro' => [
            'name' => 'Pro',
            'active' => false,
            'visible' => false,
            'assignable' => false,
            'purchasable' => false,
            'price_usd' => null,
            'currency' => 'USD',
            'interval' => 'monthly',
            'limits' => [],
        ],
        'business' => [
            'name' => 'Business',
            'active' => false,
            'visible' => false,
            'assignable' => false,
            'purchasable' => false,
            'price_usd' => null,
            'currency' => 'USD',
            'interval' => 'monthly',
            'limits' => [],
        ],
    ],
];
